{/* <div id="directionalKeys">
<img id="fullDirectionalPad" alt="a game directional pad with up down left and right" src="Images/white_directionalpad.png" usemap="#image-map">
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="image-map">
<area shape="rect" href="#" target="_self" alt="left" title="West" id="left" coords="-1,31,32,71" >
<area shape="rect" href="#"  target="_self" alt="up" title="North" id="up" coords="28,-1,72,29">
<area shape="rect" href="#"  target="_self" alt="right" title="East" id="right" coords="70,31,99,69">
<area shape="rect" href="#"  target="_self" alt="down" title="South" id="down" coords="31,72,70,99">
</map>
</div> */}